### ISSUE TITLE
Lower chance of duplicate / don't generate duplicates

### ISSUE THREAD

**Issue by huang-junwei** [chris-blay/AndroidNougatEasterEgg#5]
I use the app for a while now, and it seem like the chance of duplicate is really high, making the same cat as what I have appeared multiple times.
Is it possible to reduce the chance of the duplicate or possibly have a switch that turn off duplicate completely?

**Comment by chris-blay** [comment]
I remember feeling the same way when I first encountered this Easter Egg! I thought maybe the chance of a new cat depends on going to a new location, which is incorrect. Since we're here in the GitHub project I might as well reveal the secrets behind getting a new cat:

There are four different foods. Each food has a hard-coded "minutes until a cat arrives" and "percent chance that it is a new cat". These values are specified in https://github.com/chris-blay/AndroidNougatEasterEgg/blob/master/workspace/res/values/strings.xml but here they are in plain text:
- Bits: 15 minute delay, 5% chance of new cat
- Fish: 30 minute delay, 35% chance of new cat
- Chicken: 60 minute delay, 65% chance of new cat
- Doughnut: 120 minute delay, 90% chance of new cat (this gives the highest chance of new cats)

In the spirit of maintaining this Easter Egg as closely to its original version as possible, I will be leaving this behavior unchanged. Note the source is freely available so it's very easy to tweak the hard-coded values to make every food have 1 minute delay and 100% chance of new cat in a custom build, but would that really be an accomplishment?

**Comment by hjw163** [comment]
And here I thought they actually randomize the time delay and the chance of getting a new cat DX

**Comment by chris-blay** [comment]
No worries! I thought of a few clarifications in the meantime

**New Cat Probability**

Probability of a new cat is always 100% if there are no cats yet

Otherwise, here's how overall probability of a new cat can be objectively compared across different foods:
- Bits: In 2h there are ~8 chances to put bits out at 5% chance each time. Chance of not getting a new cat is 95%. Chance of not getting a new cat 8 times in a row is 95% to the eighth power, which is ~66%. Therefore chance of getting a new cat in 2h is ~34% if constantly refilling the bowl
- Fish: 1-(1-.35)**4=~82%
- Chicken: 1-(1-.65)**2=~88%
- Doughnut: Hardcoded 90%

So patience is definitely coded to be a virtue; doughnut is best in all cases

**Delays**

Note there's some extra random delay thrown in due to offloading the arrival of the cat (new or not) to [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler)
